name: Create production builds

on:
  push:
    branches:
      - main

jobs:
  # build_android:
  #   name: Build Android
  #   type: build
  #   params:
  #     platform: android
  #     profile: production
  build_ios:
    name: Build iOS
    type: build
    params:
      platform: ios
      profile: production
  # submit_android_build:
  #   name: Submit Android Build
  #   needs: [build_android]
  #   type: submit
  #   params:
  #     build_id: ${{ needs.build_android.outputs.build_id }}
  submit_ios_build:
    name: Submit iOS Build
    needs: [build_ios]
    type: submit
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
